WebMVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebMVC.Models
{
    public class Animal
    {
        public string Nome { get; set; }
    }
}

WebMVC/Controllers/AnimaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMVC.Models;
using WebMVC.Servicos;

namespace WebMVC.Controllers
{
    public class AnimaisController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(string nome)
        {
            AnimalServico.Instancia().Add(new Animal() { 
                Nome = nome
            });

            ViewBag.mensagem = "Cadastrado com sucesso";
            return View();
        }
    }
}

WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMVC.Servicos;

namespace WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View(AnimalServico.Instancia().Todos());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebMVC/Views/Animais/Cadastrar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="alert alert-success" role="alert">
    @ViewBag.mensagem
</div>

<hr />
<a href="/animais">Cadastrar novo</a>

WebMVC/Views/Animais/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Cadastro</h1>

<form action="/animais/cadastrar" method="post">
    <label>
        Nome:
        <input type="text" name="nome" />
        <br />
        <button type="submit">Enviar</button>
    </label>
</form>

WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Animais</h1>
    <p>
        Cadastro de  animais em memória
    </p>
    <p><a class="btn btn-default" href="/animais">Clique aqui para cadastrar</a></p>
</div>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>id</th>
            <th>Nome</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var animal in Model)
        {
            <tr>
                <td>-</td>
                <td>@animal.Nome</td>
            </tr>
        }
    </tbody>
</table>

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Index", "Animais")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>